[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "local-worker"
version = "0.1.0"
dependencies = ["ollama", "rich"]

[project.scripts]
worker = "terminal_worker.worker:start_agent"